[package]
name = "polyproto"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
description = "A helper library for the polyproto protocol"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signature = "2.2.0"
thiserror = "1.0.56"
