[package]
name = "polyproto"
version = "0.3.0"
edition = "2021"
license = "MPL-2.0"
description = "A helper library for the polyproto protocol"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
asn1-rs = { version = "0.5.2", default-features = false }
