[package]
name = "polyproto"
version = "0.5.0"
edition = "2021"
license = "MPL-2.0"
description = "(Generic) Rust types and traits to quickly get a polyproto implementation up and running"
repository = "https://github.com/polyphony-chat/polyproto"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[features]
wasm = ["dep:getrandom", "getrandom/js"]

[dependencies]
der = { version = "0.7.8", features = ["pem"] }
getrandom = { version = "0.2.12", optional = true }
spki = "0.7.3"
thiserror = "1.0.57"
x509-cert = { version = "0.2.5", default-features = false }

[dev-dependencies]
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "signature"] }
rand = "0.8.5"
polyproto = { path = "./" }
