[package]
name = "polyproto"
version = "0.9.0-alpha.2"
edition = "2021"
license = "MPL-2.0"
description = "(Generic) Rust types and traits to quickly get a polyproto implementation up and running"
repository = "https://github.com/polyphony-chat/polyproto"
rust-version = "1.65.0"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[features]
default = ["routes", "reqwest"]
wasm = ["getrandom", "getrandom/js"]
getrandom = ["dep:getrandom"]
routes = ["serde"]
reqwest = ["dep:reqwest", "routes"]
serde = ["dep:serde", "dep:serde_json", "dep:ser_der"]

[dependencies]
der = "0.7.9"
getrandom = { version = "0.2.14", optional = true }
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["json"], optional = true }
serde = { version = "1.0.199", optional = true, features = ["derive"] }
serde_json = { version = "1.0.116", optional = true }
spki = "0.7.3"
thiserror = "1.0.59"
x509-cert = { version = "0.2.5", default-features = false, features = ["pem"] }
ser_der = { version = "0.1.0-alpha.1", optional = true, features = ["alloc"] }

[dev-dependencies]
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "signature"] }
rand = "0.8.5"
polyproto = { path = "./" }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.42"
wasm-bindgen = "0.2.92"
